Small improvements for Elemental UI
rancher/elemental-ui pull request #35
Opened 2022-11-07 11:30 UTC by aalves08

-remove `yaml import` button from machine inventory list view
- add `detail` view for machine registration
- create `/dashboard` route

**Screenshots**
_Detail_
<img width="1935" alt="Screenshot 2022-11-07 at 11 18 20" src="https://user-images.githubusercontent.com/97888974/200298531-66a91dfa-a15e-4291-80ad-5598d1c0b28e.png">
_Config_
<img width="1935" alt="Screenshot 2022-11-07 at 11 18 24" src="https://user-images.githubusercontent.com/97888974/200298535-b93179e4-b6b8-4a10-8563-59651d4f6715.png">

**How to test**
- Follow instructions on how to run this repo https://github.com/rancher/elemental-ui on this branch `small-improvements-elemental-ui`

- Install `elemental-operator`
Go to Local cluster -> open kubectl shell -> install helm chart:
```
helm install --create-namespace -n cattle-elemental-system elemental-operator \
             oci://registry.opensuse.org/isv/rancher/elemental/charts/elemental/elemental-operator
```

- Update `elemental-operator`
On the same kubectl shell run:
```
helm upgrade --create-namespace -n cattle-elemental-system --install elemental-operator oci://registry.opensuse.org/isv/rancher/elemental/stable/charts/elemental/elemental-operator
```

- Enter side-menu entry `OS Management`

2022-11-09 17:17 UTC, jordojordo requested changes
A couple of nit picks - otherwise lgtm

2022-11-10 09:41 UTC, aalves08 commented on pkg/elemental/detail/elemental.cattle.io.machineregistration.vue
> +  name:       'MachineRegistrationEditView',
Correct my friend. Thanks! 🙏

2022-11-10 09:42 UTC, aalves08 commented on pkg/elemental/detail/elemental.cattle.io.machineregistration.vue
> +    }
Not used... Came as copy-paste from the edit view. Removed 🙏 Thanks

2022-11-10 12:24 UTC, jordojordo approved these changes

2022-11-10 13:45 UTC, merged